name: Test
on:
  push: # A push to any branch triggers the workflow
jobs:
  verify-code-integrity-and-run-tests:
    runs-on: ubuntu-latest # runs the job on the latest version of Ubuntu (Linux)
    steps:
      - uses: actions/checkout@v3 # pull the git repository and set it as the current working directory
      - uses: actions/setup-node@v3 # set ups Node.js in the runner
        with:
          node-version: "16"
      - name: Install Dependencies
        run: npm ci
      - name: Run Linting Checks
        run: npm run lint
      - name: Run Tests
        run: npm run tests
      - name: Build Application
        run: npm run build
